/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChatFrontEnd.java
 *
 * Created on Nov 4, 2010, 4:45:27 PM
 */

package FrontEnd;

import java.awt.GridLayout;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Administrator
 */
public class ChatFrontEnd extends javax.swing.JFrame {

    /** Creates new form BankSimulatorFrame */
    public ChatFrontEnd() {

    data = new BankData();
    setLayout(new GridLayout(0, 1));

    add(createLoadPanel());
    add(createFindPanel());
    add(createDepositPanel());

    initComponents();

  }

  private JPanel createLoadPanel()
  {
    JPanel panel = new JPanel();

    JButton loadButton = new JButton("Load");
    loadButton.setEnabled(true);
    panel.add(loadButton);

    return panel;
  }

  private JPanel createFindPanel()
  {
    JPanel panel = new JPanel();

    findButton = new JButton("Find");
    findButton.setEnabled(false);
    panel.add(findButton);

    addButton = new JButton("Add");
    addButton.setEnabled(false);
    panel.add(addButton);

    panel.add(new JLabel("Account number: "));

    final JTextField accountText = new JTextField(10);
    panel.add(accountText);

    return panel;
  }


  private JPanel createDepositPanel()
  {
    JPanel panel = new JPanel();
    depositButton = new JButton("Deposit");
    panel.add(depositButton);

    panel.add(new JLabel("Amount: "));

    final JTextField amountText = new JTextField(10);
    panel.add(amountText);

    depositButton.setEnabled(false);

    return panel;
  }

  private BankData data;
  private int currentPosition;
  private BankAccount currentAccount;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    findButton = new javax.swing.JButton();
    addButton = new javax.swing.JButton();
    accountText = new javax.swing.JTextField();
    depositButton = new javax.swing.JButton();
    amountText = new javax.swing.JTextField();
    balanceLabel = new javax.swing.JLabel();
    accountText1 = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    findButton.setText("Refresh");
    findButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        findButtonActionPerformed(evt);
      }
    });

    addButton.setText("Send");
    addButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        addButtonActionPerformed(evt);
      }
    });

    depositButton.setText("Login");
    depositButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        depositButtonActionPerformed(evt);
      }
    });

    balanceLabel.setText("Send Message:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(balanceLabel)
            .addGap(18, 18, 18)
            .addComponent(amountText))
          .addGroup(layout.createSequentialGroup()
            .addComponent(accountText, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(accountText1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(depositButton)
            .addGap(18, 18, 18)
            .addComponent(addButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(findButton)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(0, 15, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(accountText, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(accountText1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(balanceLabel)
          .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(depositButton)
          .addComponent(addButton)
          .addComponent(findButton))
        .addGap(31, 31, 31))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        try
        {
          double amount = Double.parseDouble(amountText.getText());
          currentAccount.deposit(amount);
          data.write(currentPosition, currentAccount);
          balanceLabel.setText("" + currentAccount.getBalance());
          depositButton.setEnabled(true);
        }
        catch (IOException ex)
        {
          JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        catch (NumberFormatException ex)
        {
          JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_depositButtonActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
       try
        {
          int accountNumber = Integer.parseInt(accountText.getText());
          currentPosition = data.find(accountNumber);
          if (currentPosition < 0)
          {
            currentPosition = data.size();
            currentAccount = new BankAccount(accountNumber, 0);
            data.write(currentPosition, currentAccount);
          }
          else
          {
            JOptionPane.showMessageDialog(null, "account already exists");
            currentAccount = data.read(currentPosition);
          }
          balanceLabel.setText("" + currentAccount.getBalance());
          depositButton.setEnabled(true);
        }
        catch (IOException ex)
        {
          JOptionPane.showMessageDialog(null, ex.getMessage());
          depositButton.setEnabled(false);
        }
        catch (NumberFormatException ex)
        {
          JOptionPane.showMessageDialog(null, ex.getMessage());
          depositButton.setEnabled(false);
        }
    }//GEN-LAST:event_findButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
      JOptionPane.showMessageDialog(null, "File Not Found");
          
    }//GEN-LAST:event_addButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                ChatFrontEnd frame = new ChatFrontEnd();
                frame.setTitle("ACO 420 Spring 2015 Project2: Chat App");
                frame.setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField accountText;
  private javax.swing.JTextField accountText1;
  private javax.swing.JButton addButton;
  private javax.swing.JTextField amountText;
  private javax.swing.JLabel balanceLabel;
  private javax.swing.JButton depositButton;
  private javax.swing.JButton findButton;
  // End of variables declaration//GEN-END:variables

}
